#!/bin/bash
#\033[38;2;R;G;Bm

PERCENT=$(mpstat 1 1 | tail -n 1 | awk '{printf "%.0f", 100 - $12}')
#CPU_TEMP=$(cat /sys/class/power_supply/BAT1/status)
COLOR="#68B0CA"
ICON=" "
REV=$((100 - PERCENT))
TEMP=$(avg_temp=$(sensors | awk '/^Package|^Tdie|^Core 0/ {print $3}' | sed 's/[^0-9.]//g' | awk '{sum += $1; count++} END {printf "%.0f\n", sum/count}')
echo "$avg_temp°")

if [ $REV -lt 20 ]; then
	COLOR="#CE3D27"
elif [ $REV -lt 40 ]; then
	COLOR="#D38622"
elif [ $REV -lt 60 ]; then
	COLOR="#D9DC18"
elif [ $REV -lt 80 ]; then
	COLOR="#36AE54"
fi

echo "$TEMP$ICON$(~/.config/scripts/genbar.sh $PERCENT)"
echo "$PERCENT"
echo "$COLOR"
